name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ">=0.6.13"
  # The next three provide forms.
  flutter_form_builder: ">=7.7.0"
  form_builder_validators: ">=8.4.0"
  intl: ">=0.17.0"
  flutter_riverpod: ">=2.0.2"
  flex_color_scheme: ">=6.1.1"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/beach.jpg
    - assets/images/couch.png
    - assets/images/background.png
    - assets/images/dog.png
    - assets/images/cat.png
    - assets/images/bird.png
    - assets/images/splash.png
    - assets/images/logo.png
