// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXNAr8V1Y8TNMNuTV08d72IlHEGTYZR5w',
    appId: '1:454290264097:web:f1c87dd38f2b1507225360',
    messagingSenderId: '454290264097',
    projectId: 'pet-ometer',
    authDomain: 'pet-ometer.firebaseapp.com',
    storageBucket: 'pet-ometer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVaZ-YqZMbCXkUWk2iaWeP0TWe3onyZg',
    appId: '1:454290264097:android:4aa90e10c69fe15b225360',
    messagingSenderId: '454290264097',
    projectId: 'pet-ometer',
    storageBucket: 'pet-ometer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtL4HZ4yL0eyhPKwJNZCJPFc7hG4X3zU',
    appId: '1:454290264097:ios:7a16621ce1a9716b225360',
    messagingSenderId: '454290264097',
    projectId: 'pet-ometer',
    storageBucket: 'pet-ometer.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtL4HZ4yL0eyhPKwJNZCJPFc7hG4X3zU',
    appId: '1:454290264097:ios:4db059f47d0d34ba225360',
    messagingSenderId: '454290264097',
    projectId: 'pet-ometer',
    storageBucket: 'pet-ometer.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
